SELECT ?foodName (COUNT(DISTINCT ?category) AS ?distinctCategories) (GROUP_CONCAT(DISTINCT ?category; SEPARATOR=", ") AS ?categories)
WHERE {
  ?recipe a schema:Recipe ;
          schema:name ?foodName ;
          schema:recipeCategory ?category .
}
GROUP BY ?foodName
HAVING (COUNT(DISTINCT ?category) > 1)